# Sieci neuronowe i Deep Learning
# Temat 4: Biblioteka PyTorch - wprowadzenie

## Zadanie 4.1

1. (**Generowanie danych**).
Stworzyć tensor `data_tensor` o wymiarach `(5, 3)`, który zawiera losowe liczby z przedziału od 0 do 10. Użyć funkcji `torch.randint()`.

2. (**Podstawowa analiza**).
Oblicz średnią wszystkich elementów w `data_tensor`.
Znaleźć maksymalną wartość w każdym wierszu tego tensora oraz indeksy tych maksymalnych wartości. Wykorzystać do tego celu funkcję `torch.max()` z odpowiednimi argumentami.

3. (**Dalsze przekształcenia**).
Znormalizować
`data_tensor`, tak aby wartości w każdym wierszu sumowały się do 1 (lub do 0, jeśli na wejściu cały wiersz składa się z samych zer). To oznacza, że każdy element wiersza należy podzielić przez sumę elementów w danym wierszu.
Zadbać o to, aby kod był wykonywalny także we wspomnianym przypadku wiersza złożonego z samych zer, na przykład poprzez dodanie bardzo małej wartości (np. `1e-9`) do mianownika.

4. (**Sortowanie**).
Zaimplementować funkcję, która przyjmie tensor jako argument i zwraca tensor, w którym każdy wiersz jest posortowany rosnąco. Wykorzystać do tego celu funkcję `torch.sort()`.

In [ ]:
# Instalacja PyTorch z repozytorium PyPI:
! pip install torch
# ! pip install torch==1.9.0
import torch
import numpy as np

In [ ]:

data_tensor=torch.randint(11,[5,3])
print("1.")
print(data_tensor)
print("2.")
mean_data=torch.mean(data_tensor.float())
print("Średnia:", mean_data)
max_values, max_indices = torch.max(data_tensor, dim=1)
print("Maksymalne wartości w wierszach:", max_values)
print("Indeksy tych wartości:", max_indices)
print("3.")
row_sums=torch.sum(data_tensor, dim=1, keepdim=True)
normalized = torch.where(row_sums != 0, data_tensor / row_sums, torch.zeros_like(data_tensor)
)
print("znormalizowany: ",normalized)
print("4.")

def sortowanie(tensor):
  tensor=torch.sort(tensor,dim=1)
  return tensor.values

print(sortowanie(data_tensor))



1.
tensor([[9, 5, 0],
        [3, 3, 6],
        [4, 3, 5],
        [3, 6, 4],
        [3, 4, 3]])
2.
Średnia: tensor(4.0667)
Maksymalne wartości w wierszach: tensor([9, 6, 5, 6, 4])
Indeksy tych wartości: tensor([0, 2, 2, 1, 1])
3.
znormalizowany:  tensor([[0.6429, 0.3571, 0.0000],
        [0.2500, 0.2500, 0.5000],
        [0.3333, 0.2500, 0.4167],
        [0.2308, 0.4615, 0.3077],
        [0.3000, 0.4000, 0.3000]])
4.
tensor([[0, 5, 9],
        [3, 3, 6],
        [3, 4, 5],
        [3, 4, 6],
        [3, 3, 4]])


## Zadanie 4.2

Stworzyć tensor o wymiarach `(3, 4, 2)` zawierający losowe wartości całkowite z przedziału od 1 do 100 (wyświetlić utworzony tensor). Następnie zamienić w nim drugi wymiar z trzecim (wyświetlić tensor po zamianie) i zmień kształt otrzymanego tensora na `(4, 6)`, łącząc odpowiednio jego elementy (także wyświetlić otrzymany tensor).

In [ ]:
data_tensor=torch.randint(1,101,[3, 4, 2])
print(data_tensor)
transpose_data=torch.transpose(data_tensor, 1, 2)
print("Zamieniony wymiar miejscami: ")
print(transpose_data)
data_rashape=torch.reshape(data_tensor, [4,6])
print("Zmieniony kształt: ")
print(data_rashape)

tensor([[[90, 18],
         [75, 80],
         [ 8,  7],
         [32, 30]],

        [[92, 83],
         [53, 78],
         [58, 81],
         [28, 88]],

        [[80, 95],
         [95, 67],
         [88, 50],
         [77, 31]]])
Zamieniony wymiar miejscami: 
tensor([[[90, 75,  8, 32],
         [18, 80,  7, 30]],

        [[92, 53, 58, 28],
         [83, 78, 81, 88]],

        [[80, 95, 88, 77],
         [95, 67, 50, 31]]])
Zmieniony kształt: 
tensor([[90, 18, 75, 80,  8,  7],
        [32, 30, 92, 83, 53, 78],
        [58, 81, 28, 88, 80, 95],
        [95, 67, 88, 50, 77, 31]])


## Zadanie 4.3

Utworzyć tensor `t` o wymiarach `(6, 10)`, zawierający losowe liczby z przedziału od 0 do 1. Podzielić ten tensora na dwie równe części wzdłuż kolumn, a następnie połączyć te części w jeden tensor wzdłuż nowego wymiaru, tak aby otrzymać tensor o rozmiarze `(2, 6, 5)`. Wyświetlić tensory z wszystkich etapów przekształcenia.
Sprawdzić rozmiar powstałego tensora za pomocą metody `shape`.

In [ ]:
data_tensor=torch.rand([6,10])
print(data_tensor)
split_data=torch.chunk(data_tensor, chunks= 2, dim=1)
print("tensory po podzieleniu na dwa wzdłóż kolumn")
print("Tensor 1:")
print(split_data[0])
print("Tensor 2:")
print(split_data[1])
print("tensory po połączeniu")
final_data=torch.stack(split_data, dim=0)
print(final_data)
print("wymiar finalnego tensora to", final_data.shape)

tensor([[0.5352, 0.7696, 0.9357, 0.2225, 0.4031, 0.7603, 0.5665, 0.1764, 0.1223,
         0.4334],
        [0.7674, 0.8098, 0.5936, 0.2872, 0.3203, 0.3840, 0.9770, 0.6448, 0.8231,
         0.7849],
        [0.7181, 0.2584, 0.8655, 0.1199, 0.6605, 0.4467, 0.4518, 0.4956, 0.0115,
         0.2590],
        [0.3374, 0.7303, 0.2499, 0.7520, 0.9187, 0.7638, 0.5296, 0.3239, 0.0482,
         0.2558],
        [0.4474, 0.1766, 0.0871, 0.4209, 0.2638, 0.5851, 0.8524, 0.7371, 0.1929,
         0.1062],
        [0.7185, 0.6954, 0.3655, 0.6769, 0.9062, 0.5922, 0.3994, 0.4308, 0.9770,
         0.4185]])
tensory po podzieleniu na dwa wzdłóż kolumn
Tensor 1:
tensor([[0.5352, 0.7696, 0.9357, 0.2225, 0.4031],
        [0.7674, 0.8098, 0.5936, 0.2872, 0.3203],
        [0.7181, 0.2584, 0.8655, 0.1199, 0.6605],
        [0.3374, 0.7303, 0.2499, 0.7520, 0.9187],
        [0.4474, 0.1766, 0.0871, 0.4209, 0.2638],
        [0.7185, 0.6954, 0.3655, 0.6769, 0.9062]])
Tensor 2:
tensor([[0.7603, 0.5665, 0.1764, 0.1223,

## Zadanie 4.4

Przeanalizować kod **Tworzenie zbioru danych z plików z lokalnego dysku** z notebooka z wykładu 4 (jeśli nie zostało to zrobione podczas wykładu).

## Zadanie 4.5*

Wzorując się na fragmencie kodu ,,Tworzenie zbioru danych z plików z lokalnego dysku”,
- utworzyć katalog z własnymi grafikami (podobnych rozmiarów, ale nie takich samych, około 10 sztuk, dotyczących dwóch klas, które da się zidentyfikować po nazwach plików),
- utworzyć listę ścieżek do tych plików,
- wyświetlić obrazy z powyższej listy ścieżek,
- stworzyć etykiety liczbowe (np. `0` i `1`) dla rozważanych obrazów,
- połączyć listę nazw plików (lub ścieżek) z listą etykiet (utworzyć odpowiednią klasę, która dziedziczy po klasie `torch.utils.data.Dataset`),
- utworzyć łańcuch transformacji obrazów za pomocą PyTorch i modułu `torchvision` (funkcja `transforms.Compose()`): konwersja obrazu do tensorów + zmiana rozmiaru każdego obrazu do ustalonych wcześniej wartości,
- dodać powyższe przekształcenie do zdefiniowanej wcześniej klasy typu Dataset i utworzyć instancję zaktualizowanej klasy,
- wyświetlić przekształcone obrazy.